[book]
authors = ["nihalpasham"]
language = "en"
multilingual = false
src = "src"
title = "rustBoot Documentation"

# [preprocessor]

# [preprocessor.mermaid]
# command = "mdbook-mermaid"

# [preprocessor.svgbob2]
# font_family = "Lucida Console"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/nihalpasham/rustBoot-book"
git-repository-icon = "fa-github"
default-theme = "light"
preferred-dark-theme = "ayu"